# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisitos', '0002_auto_20170724_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexidade',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complexidade', to='requisitos.Projeto'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('A', 'Administrador'), ('D', 'Desenvolvedor')], max_length=1),
        ),
        migrations.AlterField(
            model_name='prioridade',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prioridades', to='requisitos.Projeto'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='especificacao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='requisitos.Projeto'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='requisitos.Projeto'),
        ),
        migrations.DeleteModel(
            name='TipoPerfil',
        ),
    ]
