# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projeto', '0002_auto_20170725_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=125)),
                ('especificacao', models.TextField()),
                ('estado', models.CharField(choices=[('E', 'Espera'), ('A', 'Aberto'), ('F', 'Fechado'), ('C', 'Cancelado')], max_length=1)),
                ('complexidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projeto.Complexidade')),
                ('dependencias', models.ManyToManyField(related_name='_requisito_dependencias_+', to='Requisito.Requisito')),
                ('prioridade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projeto.Prioridade')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='Projeto.Projeto')),
            ],
        ),
    ]
