# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto', '0002_auto_20170725_0131'),
        ('Requisito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisito',
            name='tipo',
            field=models.ManyToManyField(to='Projeto.Tipo'),
        ),
    ]
