# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requisito', '0002_requisito_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisito',
            name='dependencias',
            field=models.ManyToManyField(related_name='dependentes', to='Requisito.Requisito'),
        ),
    ]
